services:
    mongo:
        image: mongo:8.0.20
        container_name: snippetbox_mongodb
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD} 
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb # Persist MongoDB configuration

volumes:
    mongo-data:
        driver: local
    mongo-config:
        driver: local

