services:
    mongo:
        image: mongo:8.0.20
        container_name: snippetbox_mongodb
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD} 
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
